use super::{AGENTS_BLOCK_END, AGENTS_BLOCK_START, HOOK_MARKER};

pub(super) fn agent_hook_script(branch: &str) -> String {
    format!(
        r#"#!/bin/sh
# {HOOK_MARKER}
# Generated by dart-decimate setup-hooks.
set -eu
INPUT="$(cat || true)"
case "$INPUT" in
  *"git commit"*|*"git push"*) ;;
  *) exit 0 ;;
esac
if command -v dart-decimate >/dev/null 2>&1; then
  DART_DECIMATE_BIN="dart-decimate"
elif command -v npx >/dev/null 2>&1; then
  DART_DECIMATE_BIN="npx --no-install dart-decimate"
else
  echo "dart-decimate-gate: dart-decimate binary not found; allowing command" >&2
  exit 0
fi
BASE="${{DART_DECIMATE_BASE:-{branch}}}"
OUTPUT="$($DART_DECIMATE_BIN audit . --base "$BASE" --format json --summary 2>&1)" || {{
  echo "dart-decimate-gate: dart-decimate audit failed open" >&2
  printf '%s\n' "$OUTPUT" >&2
  exit 0
}}
case "$OUTPUT" in
  *'"error":true'*|*'"error": true'*)
    echo "dart-decimate-gate: dart-decimate returned an error envelope; allowing command" >&2
    exit 0
    ;;
  *'"verdict":"fail"'*|*'"verdict": "fail"'*)
    echo "dart-decimate-gate: blocked by dart-decimate" >&2
    printf '%s\n' "$OUTPUT" >&2
    exit 2
    ;;
  *) exit 0 ;;
esac
"#
    )
}

pub(super) fn agents_block(branch: &str) -> String {
    format!(
        r#"{AGENTS_BLOCK_START}
Before any `git commit` or `git push`, run `dart-decimate audit . --base {branch} --format json --summary`. If the verdict is `fail`, fix the reported findings before retrying. Treat JSON runtime errors like `{{ "error": true }}` as non-blocking.
{AGENTS_BLOCK_END}
"#
    )
}
